// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package theme

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/airplane.svg
var resourceAirplaneSvgData []byte
var resourceAirplaneSvg = &fyne.StaticResource{
	StaticName:    "assets/airplane.svg",
	StaticContent: resourceAirplaneSvgData,
}

//go:embed assets/logo_fade.png
var resourceLogoFadePngData []byte
var resourceLogoFadePng = &fyne.StaticResource{
	StaticName:    "assets/logo_fade.png",
	StaticContent: resourceLogoFadePngData,
}

//go:embed assets/battery.svg
var resourceBatterySvgData []byte
var resourceBatterySvg = &fyne.StaticResource{
	StaticName:    "assets/battery.svg",
	StaticContent: resourceBatterySvgData,
}

//go:embed assets/brightness.svg
var resourceBrightnessSvgData []byte
var resourceBrightnessSvg = &fyne.StaticResource{
	StaticName:    "assets/brightness.svg",
	StaticContent: resourceBrightnessSvgData,
}

//go:embed assets/broken_image.svg
var resourceBrokenimageSvgData []byte
var resourceBrokenimageSvg = &fyne.StaticResource{
	StaticName:    "assets/broken_image.svg",
	StaticContent: resourceBrokenimageSvgData,
}

//go:embed assets/calculate.svg
var resourceCalculateSvgData []byte
var resourceCalculateSvg = &fyne.StaticResource{
	StaticName:    "assets/calculate.svg",
	StaticContent: resourceCalculateSvgData,
}

//go:embed assets/display.svg
var resourceDisplaySvgData []byte
var resourceDisplaySvg = &fyne.StaticResource{
	StaticName:    "assets/display.svg",
	StaticContent: resourceDisplaySvgData,
}

//go:embed assets/ethernet.svg
var resourceEthernetSvgData []byte
var resourceEthernetSvg = &fyne.StaticResource{
	StaticName:    "assets/ethernet.svg",
	StaticContent: resourceEthernetSvgData,
}

//go:embed assets/fish_logo.png
var resourceFishLogoPngData []byte
var resourceFishLogoPng = &fyne.StaticResource{
	StaticName:    "assets/fish_logo.png",
	StaticContent: resourceFishLogoPngData,
}

//go:embed assets/fyne.png
var resourceFynePngData []byte
var resourceFynePng = &fyne.StaticResource{
	StaticName:    "assets/fyne.png",
	StaticContent: resourceFynePngData,
}

//go:embed assets/icon.png
var resourceIconPngData []byte
var resourceIconPng = &fyne.StaticResource{
	StaticName:    "assets/icon.png",
	StaticContent: resourceIconPngData,
}

//go:embed assets/internet.svg
var resourceInternetSvgData []byte
var resourceInternetSvg = &fyne.StaticResource{
	StaticName:    "assets/internet.svg",
	StaticContent: resourceInternetSvgData,
}

//go:embed assets/keyboard.svg
var resourceKeyboardSvgData []byte
var resourceKeyboardSvg = &fyne.StaticResource{
	StaticName:    "assets/keyboard.svg",
	StaticContent: resourceKeyboardSvgData,
}

//go:embed assets/laptop.svg
var resourceLaptopSvgData []byte
var resourceLaptopSvg = &fyne.StaticResource{
	StaticName:    "assets/laptop.svg",
	StaticContent: resourceLaptopSvgData,
}

//go:embed assets/lock.svg
var resourceLockSvgData []byte
var resourceLockSvg = &fyne.StaticResource{
	StaticName:    "assets/lock.svg",
	StaticContent: resourceLockSvgData,
}

//go:embed assets/maximize.svg
var resourceMaximizeSvgData []byte
var resourceMaximizeSvg = &fyne.StaticResource{
	StaticName:    "assets/maximize.svg",
	StaticContent: resourceMaximizeSvgData,
}

//go:embed assets/minimize.svg
var resourceMinimizeSvgData []byte
var resourceMinimizeSvg = &fyne.StaticResource{
	StaticName:    "assets/minimize.svg",
	StaticContent: resourceMinimizeSvgData,
}

//go:embed assets/mute.svg
var resourceMuteSvgData []byte
var resourceMuteSvg = &fyne.StaticResource{
	StaticName:    "assets/mute.svg",
	StaticContent: resourceMuteSvgData,
}

//go:embed assets/notifications.svg
var resourceNotificationsSvgData []byte
var resourceNotificationsSvg = &fyne.StaticResource{
	StaticName:    "assets/notifications.svg",
	StaticContent: resourceNotificationsSvgData,
}

//go:embed assets/person.svg
var resourcePersonSvgData []byte
var resourcePersonSvg = &fyne.StaticResource{
	StaticName:    "assets/person.svg",
	StaticContent: resourcePersonSvgData,
}

//go:embed assets/pointer.png
var resourcePointerPngData []byte
var resourcePointerPng = &fyne.StaticResource{
	StaticName:    "assets/pointer.png",
	StaticContent: resourcePointerPngData,
}

//go:embed assets/power.svg
var resourcePowerSvgData []byte
var resourcePowerSvg = &fyne.StaticResource{
	StaticName:    "assets/power.svg",
	StaticContent: resourcePowerSvgData,
}

//go:embed assets/screens.svg
var resourceScreensSvgData []byte
var resourceScreensSvg = &fyne.StaticResource{
	StaticName:    "assets/screens.svg",
	StaticContent: resourceScreensSvgData,
}

//go:embed assets/sound-high.svg
var resourceSoundHighSvgData []byte
var resourceSoundHighSvg = &fyne.StaticResource{
	StaticName:    "assets/sound-high.svg",
	StaticContent: resourceSoundHighSvgData,
}

//go:embed assets/sound-low.svg
var resourceSoundLowSvgData []byte
var resourceSoundLowSvg = &fyne.StaticResource{
	StaticName:    "assets/sound-low.svg",
	StaticContent: resourceSoundLowSvgData,
}

//go:embed assets/sound-mid.svg
var resourceSoundMidSvgData []byte
var resourceSoundMidSvg = &fyne.StaticResource{
	StaticName:    "assets/sound-mid.svg",
	StaticContent: resourceSoundMidSvgData,
}

//go:embed assets/tablet.svg
var resourceTabletSvgData []byte
var resourceTabletSvg = &fyne.StaticResource{
	StaticName:    "assets/tablet.svg",
	StaticContent: resourceTabletSvgData,
}

//go:embed assets/wallpaper.svg
var resourceWallpaperSvgData []byte
var resourceWallpaperSvg = &fyne.StaticResource{
	StaticName:    "assets/wallpaper.svg",
	StaticContent: resourceWallpaperSvgData,
}

//go:embed assets/wifi.svg
var resourceWifiSvgData []byte
var resourceWifiSvg = &fyne.StaticResource{
	StaticName:    "assets/wifi.svg",
	StaticContent: resourceWifiSvgData,
}

//go:embed assets/wifi_off.svg
var resourceWifioffSvgData []byte
var resourceWifioffSvg = &fyne.StaticResource{
	StaticName:    "assets/wifi_off.svg",
	StaticContent: resourceWifioffSvgData,
}

//go:embed assets/clock.svg
var resourceClockSvgData []byte
var resourceClockSvg = &fyne.StaticResource{
	StaticName:    "assets/clock.svg",
	StaticContent: resourceClockSvgData,
}

//go:embed assets/update.svg
var resourceUpdateSvgData []byte
var resourceUpdateSvg = &fyne.StaticResource{
	StaticName:    "assets/update.svg",
	StaticContent: resourceUpdateSvgData,
}
